### ISSUE TITLE
Can't run .js script

### ISSUE THREAD

**Issue by AntDevPlus** [benweier/blizzard.js#106]
```
blizzard.js:137
      ...params,
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\ProjectW\node_modules\blizzard.js\index.js:21:18)
```
I use the latest version available with npm.
To recreate this problem I just wanted to authenticate with my Oauth client ID and secret.

**Comment by AntDevPlus** [comment]
OK it's fix we must update node.js
